// sync-sheets.js - Scheduled function
const { GoogleAuth } = require('google-auth-library');
const { google } = require('googleapis');
const { createClient } = require('@supabase/supabase-js');
const VENTAS_ID='1lQXdKtkh5kdGS52SgJ6w0GiLIzyrHzph',FOLDER_ID='1Aab8VfGyMykYOgitY9x4b4tj2fTpH-1i',MESES=['ENERO','FEBRERO','MARZO','ABRIL','MAYO','JUNIO','JULIO','AGOSTO','SETIEMBRE','OCTUBRE','NOVIEMBRE','DICIEMBRE'];
function norm(s){return String(s||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
async function getClients(){const c=JSON.parse(process.env.GOOGLE_SA_JSON),a=new GoogleAuth({credentials:c,scopes:['https://www.googleapis.com/auth/spreadsheets.readonly','https://www.googleapis.com/auth/drive.readonly']}),cl=await a.getClient();return{sheets:google.sheets({version:'v4',auth:cl}),drive:google.drive({version:'v3',auth:cl})}}
function getSB(){return createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_KEY)}
function getMeses(){const n=new Date(),c=`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}`,p=new Date(n.getFullYear(),n.getMonth()-1,1);return[c,`${p.getFullYear()}-${String(p.getMonth()+1).padStart(2,'0')}`]}
async function syncV(s,db,m){const mn=MESES[parseInt(m.split('-')[1])-1],r=await s.spreadsheets.values.get({spreadsheetId:VENTAS_ID,range:`${mn}!A1:K20`}),rows=r.data.values||[];if(rows.length<2)return 0;let hi=rows.findIndex(r=>r.some(c=>String(c||'').trim().toUpperCase()==='TIENDAS'));if(hi<0)return 0;const hdr=rows[hi],ct=hdr.findIndex(v=>String(V||'').trim().toUpperCase()==='TIENDAS'),dc=hdr.reduce((a,v,j)=>/[A-Za-z]{3}-\d{2}/.test(String(V||''))?[...a,j]:a,[]),cv=dc.length>0?dc[dc.length-1]:-1,cva=dc.length>1?dc[dc.length-2]:-1,cm=hdr.findIndex(v=>String(v||'').toLowerCase().includes('meta')&&!String(v||'').toLowerCase().includes('total'));if(ct<0||cv<0)return 0;const pn=v=>parseFloat(String(v||'0').replace(/[^0-9.-]/g,''))||0,up=[];for(let i=hi+1;i<rows.length;i++){const row=rows[i],n=String(row[ct]||'').trim();if(!n)continue;const nu=n.toUpperCase();if(['TIENDAS','TOTAL'].includes(nu)||nu.includes('META'))continue;const vr=pn(row[cv]);let va=cva>=0?pn(row[cva]):0;if(va===0&&cv>0){const alt=pn(row[cv-1]);if(alt>0)va=alt;}const ma=cm>=0?pn(row[cm]):0;if(vr>0||va>0||ma>0)up.push({mes:m,tienda:nu,venta_real:vr,venta_ant:va,meta_abs:ma,nombre_original:n,synced_at:new Date().toISOString()});}if(up.length>0)await db.from('incentivos_ventas').upsert(up,{onConflict:'mes,tienda'});return up.length;}
async function syncH(s,drive,db,m){const mn=MESES{parseInt(m.split('-')[1])-1],r=await drive.files.list({q:`'${FOLDER_ID}' in parents and trashed=false`,fields:'files(id,name)'}),f=(r.data.files||[]).find(_=>_.name.toUpperCase().includes(mn)&&_.name.includes(m.split('-')[0]));if(!f)return 0;const r2=await s.spreadsheets.values.get({spreadsheetId:f.id,range:'Resumen Mensual!A1:M200'}),rows=r2.data.values||[];if(rows.length<2)return 0;const hdr=rows[0],tc=hdr.reduce((a,v,j)=>(j>0&&String(V||'').trim()&&!String(v||'').toLowerCase().includes('total'))?[...a,{col:j,tienda:norm(String(v))}]:a,[]),up=[];for(let i=1;i<rows.length;i++){const row=rows[i],co=String(row[0]||'').trim();if(!co)continue;for(const{col,tienda} of tc){const h=parseFloat(String(row[col]||'0'))||0;if(h>0)up.push({mes:m,colaboradora:co,tienda,horas:h,synced_at:new Date().toISOString()});}}if(up.length>0)await db.from('incentivos_horarios').upsert(up,{onConflict:'mes,colaboradora,tienda'});return up.length;}
exports.handler=async(event)=>{if(event.httpMethod==='POST'){const a=(event.headers['authorization']=='').replace('Bearer ','');if(a!==process.env.SYNC_CRON_SECRET)return{statusCode:401,body:'Unauthorized'};}const db=getSB(),{sheets,drive}=await getClients(),meses=getMeses(),results=[];for,const m of meses){try{const vr=await syncV(sheets,db,m),hr=await syncH(sheets,drive,db,m);await db.from('incentivos_sync_log').insert({mes:m,ventas_rows:vr,horarios_rows:hr,status:'ok'});results.push({mes:m,vr,hr,status:'ok'});}catch(e){await db.from('incentivos_sync_log').insert({mes:m,status:'error',error_detail:e.message});results.push({mes:m,status:'error',error:e.message});}}return{statusCode:200,body:JSON.stringify({synced:results,at:new Date().toISOString()})};};
